[package]
name = "arch-disk-tui"
version = "0.1.0"
edition = "2024"
authors = ["Emir <emirlkf@hotmail.com>"]
repository = "https://github.com/emirkefi/arch-disk-tui"
description = "A blazingly fast, modern, and aesthetic Terminal Disk Space Analyzer & Treemap for Linux / Arch Linux"
readme = "README.md"
license = "MIT"
keywords = ["tui", "disk-usage", "ncdu", "ratatui", "archlinux"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29.0"
human_bytes = "0.4.3"
jwalk = "0.9.0"
ratatui = "0.30.2"
sysinfo = "0.39.6"
libc = "0.2"

